### ISSUE TITLE
Add embedded map to Edit Metadata page, so user can see what drive and locations this file pertains to

### ISSUE THREAD

**Issue by haiyan** [Safecast/safecastapi#101]

**Comment by Frangible** [comment]
As far as I know this is resolved now, unless there's a way to edit the metadata I'm not seeing.

**Comment by seanbonner** [comment]
Not resolved, the issue is that when you upload the log you are then prompted to add metadata while it's processing. You can wait for it to process before adding metadata, but if you click the "add metadata" link then you get a page without a map. The resolution should be combining those things so that:

1. Upload log
2. "processing - stay tuned"
3. "here's the map, add metadata and submit it for approval"
